### ISSUE TITLE
Schema includes doesn't work

### ISSUE THREAD

**Issue by tonjac** [Tirasa/wadl2html#2]
I have a WADL (generated with Jersey 1.17.1) that has a schema-include. This doesn't work. You can get it from here: https://www.tonjac.org/org.tonjac.schoolsoft.push-1.0-SNAPSHOT/push/application.wadl

**Comment by ilgrosso** [comment]
Just access http://localhost:8888/?remote=true to see your WADL featuring schema include.

**Comment by tonjac** [comment]
Hi, thanks but it still doesn’t work. Look att /notification/sendToGroup, request and response links should lead to the schema-doc, but the generated html is blank.

/Toni

27 nov 2013 kl. 11:22 skrev Francesco Chicchiriccò notifications@github.com:

**Comment by ilgrosso** [comment]
Yes, this happens because the code assumes that any XSD schema has a target namespace to be used for links. 
You can click the ".xsd" on top of the page to see that XSD schema is available and browseable.

Being completely unrelated to this issue, I've opened #3.

**Comment by tonjac** [comment]
If i click the ".xsd" on top of the page a see the same empty schema.html page...

----- Original Message -----

**Comment by ilgrosso** [comment]
Please update your sources: I've just tried and everything seems to be working now (there is not even ".xsd" any more but "schema.xsd").

**Comment by tonjac** [comment]
Yes, works now, thanks!
Question: Why the remote? It would be nice if it works with the local application.wadl.

28 nov 2013 kl. 13:22 skrev Francesco Chicchiriccò notifications@github.com:

**Comment by ilgrosso** [comment]
You are right: I have changed things by removing any 'remote' reference.
Update your sources, then read [README](https://github.com/Tirasa/wadl2html/blob/master/README.md) for more information.
