### ISSUE TITLE
Html Files

### ISSUE THREAD

**Issue by robrushton** [Tirasa/wadl2html#4]
Is there a way to just get the generated html files?

**Comment by ilgrosso** [comment]
We do that in [Apache Syncope](https://github.com/apache/syncope/), via Maven.

First, WADL is [generated](https://github.com/apache/syncope/blob/2_0_X/common/rest-api/pom.xml#L118-L154) via the `cxf-java2wadl-plugin`, then the WADL is [transformed into HTML pages](https://github.com/apache/syncope/blob/2_0_X/core/rest-cxf/pom.xml#L165-L262) via the `xml-maven-plugin`, e.g. essentially applying some XSLT files to the WADL file.
